name: istorija_srbije
description: "Kviz iz istorije Srbije."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.0
  flutter_sequence_animation: "^4.0.0"
  provider: ^6.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.0.8
  wakelock: ^0.6.2
  flutter_vibrate: ^1.3.0
  audioplayers: ^5.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    # - assets/user/
    - assets/questions/
    - assets/sounds/


  fonts:
    - family: ShantellSans
      fonts:
        - asset: assets/fonts/ShantellSans-Bold.ttf
        - asset: assets/fonts/ShantellSans-Regular.ttf

    - family: RubikDoodleShadow
      fonts:
        - asset: assets/fonts/RubikDoodleShadow-Regular.ttf
